#!/usr/bin/awk -f

# awk script to print all juveniles .csv file from cjis.

BEGIN {
    # Set the imput and field separator
    FS="\",\""

    # Add Field Headers
    print "\nSID     ","DOA      ","TRN     ","TRS   "  \
    ,"Child Name        " \
    ,"Disposition" \
    "\n......................................................................"

    # Zero the records counter
    records=0

}

# Strip out header
NR == 1 {next;}

{if ($14 == "J")
    {
        print records + 1,$2,$3,$4,$5,$9,$10,$14,$23;
        # Add record to counter
        records++;
    } 
}

END {
    
    # Print the results
    print ".................................................................\n"
    print records " of " NR " records.\n"

}
