#!/usr/bin/awk -f

# awk script to print all juveniles .csv file from cjis.

BEGIN {
    # Set the imput and field separator
    FS="\",\""

    # Add Field Headers
    print "\n  SID\t","   DOA\t","   TRN\t","TRS\t"  \
    ,"Child Name\t", "      Disposition" \
    ,
"\n========================================================================================"

    # Zero the records counter
    records=0

}

# Strip out header
NR == 1 {next;}

{if ($14 == "J")
    {
        printf("%s %-8s %10s %-9s %-4s %-14s %-16s %-2s %s\n", records + 1,$2,$3,$4,$5,$9,$10,$14,$23);
        # Add record to counter
        records++;
    } 
}

END {
    
    # Print the results
    print "=========================================================================================\n"
    print "Printing " records " of " NR " records.\n"

}
